### ISSUE TITLE
HTTP 401

### ISSUE THREAD

**Issue by aifuenzalida** [hrbrmstr/omdbapi#4]
> search_by_title("Captain America")
Error in search_by_title("Captain America") : Unauthorized (HTTP 401).

**Comment by hrbrmstr** [comment]
![image](https://cloud.githubusercontent.com/assets/509878/26303063/4a629186-3eb4-11e7-9c44-f216f8843cab.png)

https://www.patreon.com/posts/api-is-going-10743518

**Comment by hrbrmstr** [comment]
I'm leaving the issue open until I get my API keys and add the API key supportl
